SQLACHEMY/Sqlachemy_MVC/models/user.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import Mapped, mapped_column

db = SQLAlchemy()

class User(db.Model):
    __tablename__ = 'users'
    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str]
    senha: Mapped[str]

    def __repr__(self):
        return f'<User {self.email}>'

SQLACHEMY/Sqlachemy_MVC/app.py
from flask import Flask
from models.user import db
from controllers.usercontroller import user_controller


app = Flask(__name__, template_folder='templates')

# Configurações do banco de dados
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///database.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False  # Desabilita o rastreamento de modificações

# Inicializa o banco de dados com a app
db.init_app(app)

# Registra o Blueprint de usuários


app.register_blueprint(user_controller, url_prefix='/users')

# Cria as tabelas do banco de dados, se necessário
with app.app_context():
    db.create_all()

SQLACHEMY/Sqlachemy_MVC/controllers/usercontroller.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.user import db, User

# Cria um Blueprint para controlar as rotas relacionadas aos usuários
user_controller = Blueprint('user_controller', __name__)

# Rota para listar todos os usuários
@user_controller.route('/')
def index():
    users = User.query.all()  # Consulta todos os usuários do banco
    return render_template('pages/index.html', users=users)

# Rota para criar um novo usuário
@user_controller.route('/create', methods=['POST', 'GET'])
def create():
    if request.method == 'POST':
        user = User(
            email=request.form['email'],
            senha=request.form['senha']
        )
        db.session.add(user)
        db.session.commit()  # Confirma a adição do novo usuário
        return redirect(url_for('user_controller.index'))  # Redireciona para a lista de usuários

    return render_template('pages/create.html')

# Rota para editar um usuário existente
@user_controller.route('/<int:id>/edit', methods=['POST', 'GET'])
def edit(id):
    user = User.query.get(id)  # Busca o usuário pelo ID
    if not user:
        return redirect(url_for('error', message='Usuário não encontrado'))

    if request.method == 'POST':
        user.email = request.form['email']  # Atualiza o email do usuário
        db.session.commit()  # Confirma a alteração
        return redirect(url_for('user_controller.index'))

    return render_template('pages/edit.html', user=user)

SQLACHEMY/Sqlachemy_MVC/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQLITE 3</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

    {% block link %}
    {% endblock %}
</head>
<body>

    <div class="container">
        <div class="nav">
            <h2><a href="{{ url_for('user_controller.index') }}">Users</a></h2>
            <h2><a href="{{ url_for('user_controller.create') }}">Add</a> </h2>
        </div>
        <div class="main">
            {% block conteudo %}
            {% endblock %}
        </div>
    </div>
    
</body>
</html>

SQLACHEMY/Sqlachemy_MVC/templates/pages/create.html
{% extends 'layout.html' %}

{% block conteudo %}

<div class="users">

    <form action="{{url_for('user_controller.create')}}" method="post">
        <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
        {% with error = get_flashed_messages()  %}
        <span class="warning">{{error[0]}}</span>    
        {% endwith %}    
        <input type="password" name="senha" placeholder="Senha">
        <button>Enviar</button>
    </form>

</div>
    
{% endblock %}

SQLACHEMY/Sqlachemy_MVC/templates/pages/edit.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="users">

    <form action="{{url_for('user_controller.edit', id=user['id'])}}" method="post">
        <input type="email" name="email" placeholder="Email" value="{{user['email']}}">
        <button>Enviar</button>
    </form>

</div>
{% endblock %}

SQLACHEMY/Sqlachemy_MVC/templates/pages/index.html
{% extends 'layout.html' %}

{% block link %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
{% endblock %}

{% block conteudo %}

<div class="users">
    <ul>
        {% for user in users %}
        <li>
            <span>Email:</span> 
            {{user['email']}} 
            <a href="{{url_for('user_controller.edit', id=user['id'])}}">
                <span class="material-symbols-outlined">edit_document</span>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}