SQLACHEMY/FlaskLogin_SQLAlchemy/models/Livro.py
from sqlalchemy.orm import Mapped, mapped_column, relationship
from database import db


class Livro(db.Model):
    __tablename__ = 'livros'
    id: Mapped[int] = mapped_column(primary_key=True)
    titulo: Mapped[str] = mapped_column(db.String(150), nullable=False)
    user_id: Mapped[int] = mapped_column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    user = db.relationship('User', back_populates='livros')

SQLACHEMY/FlaskLogin_SQLAlchemy/models/User.py
from sqlalchemy.orm import Mapped, mapped_column, relationship
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from database import db

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id: Mapped[int] = mapped_column(primary_key=True)
    nome: Mapped[str] = mapped_column(db.String(150), nullable=False)
    senha_hash: Mapped[str] = mapped_column(db.String(150), nullable=False)
    livros = db.relationship('Livro', back_populates='user')

    def set_password(self, senha):
        self.senha_hash = generate_password_hash(senha)

    def check_password(self, senha):
        return check_password_hash(self.senha_hash, senha)

SQLACHEMY/FlaskLogin_SQLAlchemy/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from database import db
from models.User import User
from models.Livro import Livro
from controllers.auth_controller import auth
from flask_login import LoginManager

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///teste.db"
app.config["SECRET_KEY"] = "sua_chave_secreta_aqui"

login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

db.init_app(app)

with app.app_context():
    db.create_all()

# Registre o Blueprint
app.register_blueprint(auth)

SQLACHEMY/FlaskLogin_SQLAlchemy/controllers/auth_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from models.User import User
from models.Livro import Livro
from database import db

auth = Blueprint("auth", __name__)

@auth.route('/')
def index():
    users = db.session.execute(db.select(User).order_by(User.nome)).scalars().all()
    livros = db.session.execute(db.select(Livro).order_by(Livro.titulo)).scalars().all()
    return render_template("index.html", users=users, livros=livros)

@auth.route('/registrar_usuario', methods=['GET', 'POST'])
def registrar_usuario():
    if request.method == 'POST':
        nome = request.form['nome']
        senha = request.form['senha']
        user = User(nome=nome)
        user.set_password(senha)  # Define a senha usando o método set_password
        db.session.add(user)
        db.session.commit()
        flash('Usuário cadastrado com sucesso!', 'success')
        return redirect(url_for("auth.login"))

    return render_template("registrar_usuario.html")

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        nome = request.form['nome']
        senha = request.form['senha']
        user = User.query.filter_by(nome=nome).first()
        if user and user.check_password(senha):
            login_user(user)
            return redirect(url_for('auth.cadastrar_livro_usuario'))
        else:
            flash('Usuário ou senha incorretos.')
    return render_template('login.html')

@auth.route('/cadastrar_livro_usuario', methods=["GET", "POST"])
@login_required
def cadastrar_livro_usuario():
    if request.method == "POST":
        user_id = request.form["user_id"]
        titulo = request.form["titulo"]
        livro = Livro(titulo=titulo, user_id=user_id)
        db.session.add(livro)
        db.session.commit()
        flash('Livro cadastrado com sucesso!', 'success')
        return redirect(url_for("auth.index"))

    users = User.query.all()
    return render_template("registrar_livro_usuario.html", users=users)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.index'))

SQLACHEMY/FlaskLogin_SQLAlchemy/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <nav>
            <a href="{{ url_for('auth.cadastrar_livro_usuario') }}">Cadastrar Livros de Usuarios</a>
            <a href="{{ url_for('auth.index') }}">Pagina inicial</a>
            <a href="{{ url_for('auth.registrar_usuario') }}">Fazer cadastro de Usuarios</a>
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout </a>
        </nav>
        <h2>Usuários</h2>
        <ul>
            {% for user in users %}
            <li>
                <span>Nome:</span> {{ user.nome }}
            </li>
            {% endfor %}
        </ul>

        <h2>Livros</h2>
        <ul>
            {% for livro in livros %}
            <li>
                <span>Título:</span> {{ livro.titulo }}
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

SQLACHEMY/FlaskLogin_SQLAlchemy/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{{ url_for('auth.login') }}" method="post">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required><br><br>

        <label for="senha">Senha:</label>
        <input type="password" id="senha" name="senha" required><br><br>
        
        <button type="submit">Login</button>
    </form>
</body>
</html>

SQLACHEMY/FlaskLogin_SQLAlchemy/templates/registrar_livro_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cadastrar Livro de Usuário</h1>
    <form action="{{ url_for('auth.cadastrar_livro_usuario') }}" method="post">
        <label for="user_id">Selecione o Usuário:</label>
        <select id="user_id" name="user_id" required>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.nome }}</option>
            {% endfor %}
        </select><br><br>

        <label for="titulo">Título do Livro:</label>
        <input type="text" id="titulo" name="titulo" required><br><br>
        
        <button type="submit">Cadastrar</button>
    </form>
</body>
</html>

SQLACHEMY/FlaskLogin_SQLAlchemy/templates/registrar_usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Usuário</title>
</head>
<body>
    <h1>Cadastrar Usuário</h1>
    <form action="{{ url_for('auth.registrar_usuario') }}" method="post">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required><br><br>

        <label for="senha">Senha:</label>
        <input type="password" id="senha" name="senha" required><br><br>

        <button type="submit">Cadastrar Usuário</button>
    </form>
</body>
</html>